#!/usr/bin/env node
/**
 * drug-safety-mcp - MCP Server Entry Point
 * 
 * Core functionality comes from @sineai/mcp-core package.
 * Your tools are in src/tools/ - that's where you add your custom logic.
 * 
 * To update core (security fixes, new features):
 *   npm run update:core
 * 
 * @generated by mcp-forge v2.0.0
 */

import "dotenv/config";
import {
  secrets,
  CONFIG,
  initStaticConfig,
  loadAuthConfig,
  runLocal,
  runRemote,
  audit,
} from "@sineai/mcp-core";
import { TOOLS, handleTool } from "./tools/index.js";

// Server info
const NAME = "drug-safety-mcp";
const VERSION = "1.0.0";

async function main(): Promise<void> {
  // 1. Initialize configuration
  initStaticConfig(NAME, VERSION);
  
  // 2. Initialize secrets manager (Key Vault)
  await secrets.initialize();
  
  // 3. Load auth config from Key Vault
  await loadAuthConfig();
  
  // 4. Start server in appropriate mode
  if (CONFIG.mode === "remote") {
    await runRemote(TOOLS, handleTool);
  } else {
    await runLocal(TOOLS, handleTool);
  }
}

main().catch((error: Error) => {
  audit({ level: "error", event: "fatal", error: error.message });
  console.error("Fatal error:", error);
  process.exit(1);
});
